services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rubeusintegration-app
    restart: always
    ports:
      - "3333:3333"

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: rubeusintegration
      POSTGRES_DATABASE: rubeusintegration

    depends_on:
      - db

    networks:
      - rubeusintegration-network

  db:
    image: postgres:latest
    command: [ 'postgres', '-c', 'log_statement=all' ]
    container_name: postgres
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "postgres" ]
      interval: 5s
      retries: 10

    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: rubeusintegration
      POSTGRES_DATABASE: rubeusintegration
    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - rubeusintegration-network

volumes:
  postgres-data:


networks:
  rubeusintegration-network:
    driver: bridge
